### PR TITLE
Use parser tests from the graphql gem

### PR DESCRIPTION
**Pull request by staugaard**
Unfortunately they don't pass 😢

### CODE REVIEW

**Comment by rmosolgo** [comment]
It looks like a good number would be fixed by 0.5.0 but it has some breaking changes: 

https://github.com/graphql/libgraphqlparser/releases

**Comment by rmosolgo** [comment]
Let's see what we can do!

**Comment by rmosolgo** [comment]
Looks to me like the tests fail in a few different ways: 
- Libgraphqlparser's errors don't match  graphql-ruby's 
  
  ```
  test_0004_rejects unsupported characters                        FAIL (0.00s)
  Minitest::Assertion:         [GraphQL::ParseError] exception expected, not
      Class: <GraphQL::Libgraphqlparser::ParseError>
      Message: <"1.8: unrecognized character ;">
  ```
  
  I think this needs: 
  - a mechanism for rescuing `LibgraphqlParser::ParseError` & re-raising a `GraphQL::ParseError` 
  - some loosening of the shared tests to not test specific messages (maybe, move specific tests into graphql-ruby, then generalize in the shared tests?)
  - or, add a duck-typing API where parse errors must expose the token which caused an error? 
- Libgraphqlparser doesn't parse the schema language, but graphql-ruby's parser _does_: 
  
  ```
  test_0002_parses mimal schema definition                       ERROR (0.00s)
    GraphQL::Libgraphqlparser::ParseError:         GraphQL::Libgraphqlparser::ParseError: 1.1-6: syntax error, unexpected IDENTIFIER, expecting fragment or mutation or query or {
  ```
- Some parts of the shared tests still depend on graphql-ruby test suite `DummySchema`. I get this after updating to 0.5 locally: 
  
  ```
  test_0001_parses the test schema                               ERROR (0.00s)
    NameError:         NameError: uninitialized constant GraphQL::Language::ParserTests::DummySchema
            /Users/rmosolgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/graphql-0.18.6/lib/graphql/language/parser_tests.rb:280:in `block (4 levels) in included'
  ```
- Libgraphqlparser genuinely behaves differently than graphql-ruby's parser 
  
  ```
  GraphQL::Libgraphqlparser::Parser Tests::whitespace::whitespace-only queries
    test_0001_doesn't blow up                                      ERROR (0.00s)
    GraphQL::ParseError:         GraphQL::ParseError: 1.2: syntax error, unexpected EOF
            /Users/rmosolgo/projects/graphql-libgraphqlparser/lib/graphql/libgraphqlparser.rb:14:in `rescue in parse'
  ```

**Comment by staugaard** [comment]
I'm surprised that you merged this while it was failing.

**Comment by rmosolgo** [comment]
I thought they were _all_ update-related, since the message was 

```
 expecting fragment or mutation or query or {
```

and I know that 0.5 added subscription support 😬

**Pull request merged**
